mysql:
  datasource:
    primary:
      url: jdbc:mysql://192.168.168.48:3306/primary?useUnicode=true&characterEncoding=utf-8
      username: root
      password: Hyron@123
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60
      maxLifetime: 20000
      maxPoolSize: 25
      minPoolSize: 3
    second:
      url: jdbc:mysql://192.168.168.48:3306/second?useUnicode=true&characterEncoding=utf-8
      username: root
      password: Hyron@123
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60
      maxLifetime: 20000
      maxPoolSize: 25
      minPoolSize: 3